import { Scale, AlertCircle, FileCheck, ShieldAlert, Award } from 'lucide-react';

export default function TermsAndConditions({ onNavigate }) {
  return (
    <article className="panel legal-panel">
      <header className="legal-header">
        <div className="title-with-icon">
          <Scale size={24} className="icon-accent" />
          <h1>Terms and Conditions</h1>
        </div>
        <p className="legal-meta">
          <strong>Effective Date:</strong> January 1, 2026 | <strong>Last Updated:</strong> March 2026 | <strong>Operating Entity:</strong> Ledger Technologies
        </p>
      </header>

      <div className="legal-body">
        {/* STRICT FINANCIAL DISCLAIMER CALLOUT */}
        <section className="legal-callout warning">
          <div className="flex-align gap-8 margin-bottom-8">
            <AlertCircle size={20} className="text-warning" />
            <h3>Important Disclaimer: No Financial or Investment Advice</h3>
          </div>
          <p>
            Ledger is strictly an automated personal bookkeeping, expense recording, and budgeting calculation utility.
            The software, its algorithms, automated budget alerts, financial pulse indicators, and analytics summaries do NOT constitute certified financial planning, tax accounting, investment advisory, or legal counsel.
            Ledger Technologies does not provide personalized investment recommendations. Always consult a licensed Chartered Accountant (CA), Certified Financial Planner (CFP), or registered investment advisor for financial and tax planning decisions.
          </p>
        </section>

        <section className="legal-section">
          <h2>1. Agreement to Terms</h2>
          <p>
            By accessing, creating an account, or utilizing the web or mobile applications provided by Ledger Technologies (&quot;Ledger&quot;, &quot;we&quot;, &quot;us&quot;), you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions. If you do not agree, you must discontinue use of the platform immediately.
          </p>
        </section>

        <section className="legal-section">
          <h2>2. Eligibility and Account Responsibilities</h2>
          <ul className="legal-list">
            <li><strong>Age Requirement:</strong> You must be at least 18 years of age or the age of legal majority in your jurisdiction to use Ledger independently.</li>
            <li><strong>Credential Security:</strong> You are responsible for safeguarding your login password and active session tokens. You must promptly notify us at security@ledger.app if you suspect unauthorized access to your account.</li>
            <li><strong>Data Accuracy:</strong> You acknowledge that calculations, reports, and insights generated by Ledger reflect solely the transaction records and numbers you enter. Ledger assumes no liability for inaccurate user inputs.</li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>3. Permitted and Prohibited Conduct</h2>
          <p>You agree to use Ledger solely for legitimate personal or authorized business financial record keeping. You agree NOT to:</p>
          <ul className="legal-list">
            <li>Engage in automated scraping, denial-of-service attacks, rate-limit bypassing, or unauthorized vulnerability probing.</li>
            <li>Attempt to reverse-engineer, decompile, or extract the underlying source code of proprietary services.</li>
            <li>Store illegal transaction records, fraudulent documents, or unauthorized copyrighted materials in receipt attachments.</li>
            <li>Impersonate any person or entity or misrepresent affiliation with any financial institution.</li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>4. Intellectual Property and Copyright Notice</h2>
          <p>
            All interface designs, branding, logos, graphic assets, database schemas, codebases, documentation, and feature architectures are the exclusive property of Ledger Technologies and its founder, Pradeep Basha, protected under Indian and international copyright, trademark, and trade secret laws.
          </p>
          <div className="legal-info-card">
            <p><strong>Copyright Notice:</strong> &copy; 2026 Ledger Technologies. All rights reserved.</p>
            <p><strong>Trademarks:</strong> &quot;Ledger&quot;, the Ledger logo, and associated visual designs are proprietary trade dress of Ledger Technologies.</p>
          </div>
        </section>

        <section className="legal-section">
          <h2>5. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by applicable law, in no event shall Ledger Technologies, its directors, developers, or affiliates be liable for any direct, indirect, incidental, punitive, or consequential damages resulting from:
          </p>
          <ul className="legal-list">
            <li>Errors, discrepancies, or omissions in budgeting metrics or third-party bank syncing.</li>
            <li>Data loss resulting from unbacked browser cache resets, network outages, or device corruption.</li>
            <li>Financial decisions, investments, purchases, or tax filings made on the basis of metrics displayed in the application.</li>
          </ul>
          <p>
            Our aggregate liability for all claims arising under these terms shall not exceed the amount actually paid by you to Ledger during the twelve (12) months preceding the claim, or INR 1,000 / USD $15, whichever is lower.
          </p>
        </section>

        <section className="legal-section">
          <h2>6. Termination and Account Erasure</h2>
          <p>
            You may terminate this agreement at any time by exercising your Right to Erasure in the Settings tab, which immediately deletes your profile and all stored transactions. Ledger reserves the right to suspend or terminate accounts that breach these Terms without prior liability.
          </p>
        </section>

        <section className="legal-section">
          <h2>7. Governing Law and Jurisdiction</h2>
          <p>
            These Terms and any dispute arising out of or related to them shall be governed by and construed in accordance with the substantive laws of India, without regard to conflict-of-law principles. The competent civil courts located in Bangalore, Karnataka, India shall have exclusive jurisdiction to settle any disputes.
          </p>
        </section>

        <section className="legal-section">
          <h2>8. Contact Information</h2>
          <p>For questions or formal legal notices concerning these Terms, contact:</p>
          <div className="legal-info-card">
            <p><strong>Entity:</strong> Ledger Technologies</p>
            <p><strong>Legal Department:</strong> legal@ledger.app</p>
            <p><strong>Address:</strong> Indiranagar, Bangalore, Karnataka 560038, India</p>
          </div>
        </section>
      </div>

      <footer className="legal-footer flex-between">
        <button type="button" className="btn btn-secondary" onClick={() => onNavigate('dashboard')}>
          Back to Dashboard
        </button>
        <button type="button" className="btn btn-primary" onClick={() => onNavigate('cookies')}>
          View Cookie Policy
        </button>
      </footer>
    </article>
  );
}
